name: DiT
channels:
  - pytorch
  - nvidia
dependencies:
  - python >= 3.8
  - pip:
    - torch
    - torchvision
    - timm
    - diffusers
    - accelerate
    - opencv-python-headless
    - ruamel.yaml
    - easydict
    - einops
    - flash-attn --no-build-isolation
