pip install jedi
pip install ninja
pip install timm
pip install diffusers
pip install accelerate
pip install opencv-python-headless
pip install ruamel.yaml
pip install easydict
pip install einops
pip install torchdiffeq
pip install transformers
pip install sentencepiece
