model:
    hidden_size: 128
    depth: 6
    mlp_ratio: 2.0
    cross_layers: [1, 3, 5]
    num_heads: 8

dataset: MNISTPermutedDataset

data:
    num_classes: -1
    in_channels: 3 # Input Channel
    condition_node_num: 16
    condition_node_dim: 3

diffusion:
    noise_schedule: "linear"
    diffusion_steps: 1000
