model:
    depth: 16
    mlp_ratio: 2.0
    cross_layers: [1, 3, 5, 7, 9, 11, 13, 15]
    num_heads: 8
    add_inject: true
    pos_emedding_version: "v2"

data:
    num_classes: -1
    octree_root_num: 64
    unit_length_list: [361, 139, 139]

diffusion:
    noise_schedule: "xg_linear"
    diffusion_steps: 1000

vae:
    latent_ratio: 4
    layer_num: 8
